package com.tgwrist.app.utils

import org.drinkless.tdlib.TdApi

/**
 * TDLib Message 的结构性复制
 * 用于 Compose 列表稳定性（非常重要）
 */
fun TdApi.Message.copy(
    id: Long = this.id,
    senderId: TdApi.MessageSender = this.senderId,
    chatId: Long = this.chatId,
    sendingState: TdApi.MessageSendingState? = this.sendingState,
    schedulingState: TdApi.MessageSchedulingState? = this.schedulingState,
    isOutgoing: Boolean = this.isOutgoing,
    isPinned: Boolean = this.isPinned,
    isFromOffline: Boolean = this.isFromOffline,
    canBeSaved: Boolean = this.canBeSaved,
    hasTimestampedMedia: Boolean = this.hasTimestampedMedia,
    isChannelPost: Boolean = this.isChannelPost,
    isPaidStarSuggestedPost: Boolean = this.isPaidStarSuggestedPost,
    isPaidTonSuggestedPost: Boolean = this.isPaidTonSuggestedPost,
    containsUnreadMention: Boolean = this.containsUnreadMention,
    date: Int = this.date,
    editDate: Int = this.editDate,
    forwardInfo: TdApi.MessageForwardInfo? = this.forwardInfo,
    importInfo: TdApi.MessageImportInfo? = this.importInfo,
    interactionInfo: TdApi.MessageInteractionInfo? = this.interactionInfo,
    unreadReactions: Array<TdApi.UnreadReaction>? = this.unreadReactions?.copyOf(),
    factCheck: TdApi.FactCheck? = this.factCheck,
    suggestedPostInfo: TdApi.SuggestedPostInfo? = this.suggestedPostInfo,
    replyTo: TdApi.MessageReplyTo? = this.replyTo,
    topicId: TdApi.MessageTopic? = this.topicId,
    selfDestructType: TdApi.MessageSelfDestructType? = this.selfDestructType,
    selfDestructIn: Double = this.selfDestructIn,
    autoDeleteIn: Double = this.autoDeleteIn,
    viaBotUserId: Long = this.viaBotUserId,
    senderBusinessBotUserId: Long = this.senderBusinessBotUserId,
    senderBoostCount: Int = this.senderBoostCount,
    senderTag: String = this.senderTag,
    paidMessageStarCount: Long = this.paidMessageStarCount,
    authorSignature: String = this.authorSignature,
    mediaAlbumId: Long = this.mediaAlbumId,
    effectId: Long = this.effectId,
    restrictionInfo: TdApi.RestrictionInfo? = this.restrictionInfo,
    summaryLanguageCode: String = this.summaryLanguageCode,
    content: TdApi.MessageContent = this.content,
    replyMarkup: TdApi.ReplyMarkup? = this.replyMarkup
): TdApi.Message {

    return TdApi.Message(
        id,
        senderId,
        chatId,
        sendingState,
        schedulingState,
        isOutgoing,
        isPinned,
        isFromOffline,
        canBeSaved,
        hasTimestampedMedia,
        isChannelPost,
        isPaidStarSuggestedPost,
        isPaidTonSuggestedPost,
        containsUnreadMention,
        date,
        editDate,
        forwardInfo,
        importInfo,
        interactionInfo,
        unreadReactions,
        factCheck,
        suggestedPostInfo,
        replyTo,
        topicId,
        selfDestructType,
        selfDestructIn,
        autoDeleteIn,
        viaBotUserId,
        senderBusinessBotUserId,
        senderBoostCount,
        senderTag,
        paidMessageStarCount,
        authorSignature,
        mediaAlbumId,
        effectId,
        restrictionInfo,
        summaryLanguageCode,
        content,
        replyMarkup
    )
}
